package Entity;
// Generated Oct 22, 2019 2:33:55 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Hoadon generated by hbm2java
 */
public class Hoadon  implements java.io.Serializable {


     private Serializable maHoaDon;
     private Nhanvien nhanvien;
     private Serializable tenKhachHang;
     private Date ngaylap;
     private ChiTietHoaDon chiTietHoaDon;

    public Hoadon() {
    }

	
    public Hoadon(Serializable maHoaDon, Nhanvien nhanvien) {
        this.maHoaDon = maHoaDon;
        this.nhanvien = nhanvien;
    }
    public Hoadon(Serializable maHoaDon, Nhanvien nhanvien, Serializable tenKhachHang, Date ngaylap, ChiTietHoaDon chiTietHoaDon) {
       this.maHoaDon = maHoaDon;
       this.nhanvien = nhanvien;
       this.tenKhachHang = tenKhachHang;
       this.ngaylap = ngaylap;
       this.chiTietHoaDon = chiTietHoaDon;
    }
   
    public Serializable getMaHoaDon() {
        return this.maHoaDon;
    }
    
    public void setMaHoaDon(Serializable maHoaDon) {
        this.maHoaDon = maHoaDon;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public Serializable getTenKhachHang() {
        return this.tenKhachHang;
    }
    
    public void setTenKhachHang(Serializable tenKhachHang) {
        this.tenKhachHang = tenKhachHang;
    }
    public Date getNgaylap() {
        return this.ngaylap;
    }
    
    public void setNgaylap(Date ngaylap) {
        this.ngaylap = ngaylap;
    }
    public ChiTietHoaDon getChiTietHoaDon() {
        return this.chiTietHoaDon;
    }
    
    public void setChiTietHoaDon(ChiTietHoaDon chiTietHoaDon) {
        this.chiTietHoaDon = chiTietHoaDon;
    }




}


