package Entity;
// Generated Oct 22, 2019 2:33:55 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Nhanvien generated by hbm2java
 */
public class Nhanvien  implements java.io.Serializable {


     private Serializable maNhanVien;
     private Serializable tenNhanVien;
     private Boolean gioitinh;
     private Serializable ngaySinh;
     private Integer soDienThoai;
     private Serializable diaChi;
     private Serializable chucVu;
     private Integer luong;
     private Serializable email;
     private Set hoadons = new HashSet(0);

    public Nhanvien() {
    }

	
    public Nhanvien(Serializable maNhanVien) {
        this.maNhanVien = maNhanVien;
    }
    public Nhanvien(Serializable maNhanVien, Serializable tenNhanVien, Boolean gioitinh, Serializable ngaySinh, Integer soDienThoai, Serializable diaChi, Serializable chucVu, Integer luong, Serializable email, Set hoadons) {
       this.maNhanVien = maNhanVien;
       this.tenNhanVien = tenNhanVien;
       this.gioitinh = gioitinh;
       this.ngaySinh = ngaySinh;
       this.soDienThoai = soDienThoai;
       this.diaChi = diaChi;
       this.chucVu = chucVu;
       this.luong = luong;
       this.email = email;
       this.hoadons = hoadons;
    }
    public Nhanvien(String nV01, String nguyen_Ngoc_thien, String nam, String string, String string0, String _Cầu_giấy, String nhân_viên_kho, String string1, String thiengmailcom) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Nhanvien(String text, String text0, boolean gt, Date ngaysinh, String text1, String text2, String toString, String text3, String text4) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
    public Serializable getMaNhanVien() {
        return this.maNhanVien;
    }
    
    public void setMaNhanVien(Serializable maNhanVien) {
        this.maNhanVien = maNhanVien;
    }
    public Serializable getTenNhanVien() {
        return this.tenNhanVien;
    }
    
    public void setTenNhanVien(Serializable tenNhanVien) {
        this.tenNhanVien = tenNhanVien;
    }
    public Boolean getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(Boolean gioitinh) {
        this.gioitinh = gioitinh;
    }
    public Serializable getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Serializable ngaySinh) {
        this.ngaySinh = ngaySinh;
    }
    public Integer getSoDienThoai() {
        return this.soDienThoai;
    }
    
    public void setSoDienThoai(Integer soDienThoai) {
        this.soDienThoai = soDienThoai;
    }
    public Serializable getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(Serializable diaChi) {
        this.diaChi = diaChi;
    }
    public Serializable getChucVu() {
        return this.chucVu;
    }
    
    public void setChucVu(Serializable chucVu) {
        this.chucVu = chucVu;
    }
    public Integer getLuong() {
        return this.luong;
    }
    
    public void setLuong(Integer luong) {
        this.luong = luong;
    }
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Set getHoadons() {
        return this.hoadons;
    }
    
    public void setHoadons(Set hoadons) {
        this.hoadons = hoadons;
    }




}


