package Entity;
// Generated Oct 22, 2019 2:33:55 AM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Serializable tentaikhoan;
     private Serializable matkhau;
     private Serializable chucnang;

    public Users() {
    }

    public Users(Serializable tentaikhoan, Serializable matkhau, Serializable chucnang) {
       this.tentaikhoan = tentaikhoan;
       this.matkhau = matkhau;
       this.chucnang = chucnang;
    }
   
    public Serializable getTentaikhoan() {
        return this.tentaikhoan;
    }
    
    public void setTentaikhoan(Serializable tentaikhoan) {
        this.tentaikhoan = tentaikhoan;
    }
    public Serializable getMatkhau() {
        return this.matkhau;
    }
    
    public void setMatkhau(Serializable matkhau) {
        this.matkhau = matkhau;
    }
    public Serializable getChucnang() {
        return this.chucnang;
    }
    
    public void setChucnang(Serializable chucnang) {
        this.chucnang = chucnang;
    }




}


