/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JInternalFrame;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author Dell
 */
public class FrmMain extends javax.swing.JFrame {

    String nhiemvu;
    String manv;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
       

    }

    FrmMain(String chucnang, String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        mnNhanVien = new javax.swing.JMenuItem();
        mnHangHoa = new javax.swing.JMenuItem();
        mnHoaDon = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnDangnhap = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenu4.setText("Chức năng");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        mnNhanVien.setText("Quản lý nhân viên ");
        mnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNhanVienActionPerformed(evt);
            }
        });
        jMenu4.add(mnNhanVien);

        mnHangHoa.setText("Quản lý hàng hóa");
        mnHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnHangHoaActionPerformed(evt);
            }
        });
        jMenu4.add(mnHangHoa);

        mnHoaDon.setText("Quản lý hóa đơn");
        mnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnHoaDonActionPerformed(evt);
            }
        });
        jMenu4.add(mnHoaDon);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Hệ thống");

        mnDangnhap.setText("Đăng xuất");
        mnDangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDangnhapActionPerformed(evt);
            }
        });
        jMenu3.add(mnDangnhap);
        jMenu3.add(jSeparator1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnDangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDangnhapActionPerformed
        nhiemvu = "";
        manv = "";
        jDesktopPane1.removeAll();

        new DangNhap().setVisible(true);
        dispose();


    }//GEN-LAST:event_mnDangnhapActionPerformed

    private void mnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNhanVienActionPerformed
        QuanLyNhanVien NhanVien = new QuanLyNhanVien();
        NhanVien.setVisible(true);
        this.jDesktopPane1.add(NhanVien);


    }//GEN-LAST:event_mnNhanVienActionPerformed

    private void mnHangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnHangHoaActionPerformed
        FrmQuanLyHangHoa HangHoa = new FrmQuanLyHangHoa();
        HangHoa.setVisible(true);
        this.jDesktopPane1.add(HangHoa);


    }//GEN-LAST:event_mnHangHoaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(1); // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void mnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnHoaDonActionPerformed
        FrmHoaDon HoaDon = new FrmHoaDon();
        HoaDon.setVisible(true);
        this.jDesktopPane1.add(HoaDon);
    }//GEN-LAST:event_mnHoaDonActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed

    }//GEN-LAST:event_jMenu4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnDangnhap;
    private javax.swing.JMenuItem mnHangHoa;
    private javax.swing.JMenuItem mnHoaDon;
    private javax.swing.JMenuItem mnNhanVien;
    // End of variables declaration//GEN-END:variables
}
